var app_data = [
	{
		"id": 0,
		"name": "Eva",
		"hotel_name": "Sunset Willow Resort",
		"image": "https://preview.ibb.co/ivpH07/alex_block_354270_unsplash.jpg",
		"rate": 5,
		"more_activities": true,
		"activities_number": 6,
		"commented": 5,
		"peers": 46,
		"discussions": 29,
		"findings": 19,
		"questions": 10,
		"activity_level": 2
	},
	{
		"id": 1,
		"name": "Andrew",
		"hotel_name": "Mirror Hotel",
		"image": "https://preview.ibb.co/nbDc07/chuttersnap_221987_unsplash.jpg",
		"rate": 4,
		"more_activities": true,
		"activities_number": 3,
		"commented": 4,
		"peers": 15,
		"discussions": 46,
		"findings": 23,
		"questions": 77,
		"activity_level": 3
	},
	{
		"id": 2,
		"name": "Joseph",
		"hotel_name": "Ruby Garden Hotel",
		"image": "https://preview.ibb.co/gK1fL7/daniil_vnoutchkov_397278_unsplash.jpg",
		"rate": 2,
		"more_activities": false,
		"commented": 3,
		"is_new": true,
		"peers": 11,
		"discussions": 40,
		"findings": 35,
		"questions": 21,
		"activity_level": 1
	},
	{
		"id": 3,
		"name": "Eva",
		"hotel_name": "Fairyland Resort",
		"image": "https://preview.ibb.co/fmxLL7/rktkn_111844_unsplash.jpg",
		"rate": 5,
		"more_activities": true,
		"activities_number": 2,
		"commented": 4,
		"is_new": true,
		"peers": 74,
		"discussions": 23,
		"findings": 64,
		"questions": 2
	},
	{
		"id": 4,
		"name": "Andrew",
		"hotel_name": "Regal Spring Hotel",
		"image": "https://preview.ibb.co/eD6ann/shane_hauser_140922_unsplash.jpg",
		"rate": 1,
		"more_activities": false,
		"commented": 2,
		"is_new": true,
		"peers": 85,
		"discussions": 2,
		"findings": 1,
		"questions": 12
	},
	{
		"id": 5,
		"name": "Andrew",
		"hotel_name": "Sunny Park Hotel",
		"image": "https://preview.ibb.co/h5xgSn/scott_webb_67607_unsplash.jpg",
		"rate": 4,
		"more_activities": false,
		"commented": 4,
		"is_new": true,
		"peers": 44,
		"discussions": 33,
		"findings": 88,
		"questions": 123
	},
	{
		"id": 6,
		"name": "Marek",
		"hotel_name": "Modest Nugget Hotel",
		"image": "https://preview.ibb.co/bBxsYS/christoph_schulz_559688_unsplash.jpg",
		"rate": 3,
		"more_activities": true,
		"activities_number": 7,
		"commented": 4,
		"is_new": true,
		"peers": 41,
		"discussions": 32,
		"findings": 11,
		"questions": 33
	},
	{
		"id": 7,
		"name": "Arek",
		"hotel_name": "Light Shore Resort",
		"image": "https://preview.ibb.co/k237YS/park_troopers_221404_unsplash.jpg",
		"rate": 2,
		"more_activities": true,
		"activities_number": 4,
		"commented": 1,
		"is_new": true,
		"peers": 87,
		"discussions": 34,
		"findings": 73,
		"questions": 34
	},
	{
		"id": 8,
		"name": "Jarek",
		"hotel_name": "Crown Hotel",
		"image": "https://preview.ibb.co/eoD207/nichlas_andersen_225986_unsplash.jpg",
		"rate": 5,
		"more_activities": true,
		"activities_number": 91,
		"commented": 3,
		"is_new": true,
		"peers": 12,
		"discussions": 12,
		"findings": 5,
		"questions": 7
	},
	// New data schema. All data will be dynamic by adding to DB
	{
		"hotel_name": "Crown Hotel",
		"hotel_adress": {
			"adress": "Stare miasto",
			"city": "Wrocław",
			"province": "Dolnośląskie",
			"distance": 1.3
		},
		"description": "Lorem ipsum dolor sit amet",
		"hotel_stars": 5,
		"hotel_rating": 8.4, // Depends on that show "Good, very good, poor etc."
		"opinions": 831,
		"is_new": true,
		"is_apartment": true,
		"facilities": {
			"restaurant": true,
			"gym": false,
			"wifi": true,
			"card_payment": true,
			"game_room": false
		}
	}
];

export default app_data;