language: node_js
node_js:
  - "6"
install:
  - cd client && npm install
script:
  - cd client && npm run test
after_script:
  - cd client && COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run test-ci