var app_data = [
	{
		"id": 0,
		"name": "Eva",
		"question": "Sunset Willow Resort",
		"image": "https://preview.ibb.co/ivpH07/alex_block_354270_unsplash.jpg",
		"member": "5 months",
		"last_seen": "Saturday afternoon",
		"more_activities": true,
		"activities_number": 6,
		"commented": 5,
		"peers": 46,
		"discussions": 29,
		"findings": 19,
		"questions": 10,
		"activity_level": 2
	},
	{
		"id": 1,
		"name": "Andrew",
		"question": "Mirror Hotel",
		"image": "https://preview.ibb.co/nbDc07/chuttersnap_221987_unsplash.jpg",
		"member": "1 year",
		"last_seen": "8 hours",
		"more_activities": true,
		"activities_number": 3,
		"commented": 4,
		"peers": 15,
		"discussions": 46,
		"findings": 23,
		"questions": 77,
		"activity_level": 3
	},
	{
		"id": 2,
		"name": "Joseph",
		"question": "Ruby Garden Hotel",
		"image": "https://preview.ibb.co/gK1fL7/daniil_vnoutchkov_397278_unsplash.jpg",
		"member": "2 months",
		"last_seen": "2 months ago",
		"more_activities": false,
		"commented": 3,
		"is_new": true,
		"peers": 11,
		"discussions": 40,
		"findings": 35,
		"questions": 21,
		"activity_level": 1
	},
	{
		"id": 3,
		"name": "Eva",
		"question": "Fairyland Resort",
		"image": "https://preview.ibb.co/fmxLL7/rktkn_111844_unsplash.jpg",
		"member": "9 months",
		"last_seen": "Wednesday",
		"more_activities": true,
		"activities_number": 2,
		"commented": 4,
		"is_new": true,
		"peers": 74,
		"discussions": 23,
		"findings": 64,
		"questions": 2
	},
	{
		"id": 4,
		"name": "Andrew",
		"question": "Regal Spring Hotel",
		"image": "https://preview.ibb.co/eD6ann/shane_hauser_140922_unsplash.jpg",
		"member": "3 years",
		"last_seen": "Friday morning",
		"more_activities": false,
		"commented": 2,
		"is_new": true,
		"peers": 85,
		"discussions": 2,
		"findings": 1,
		"questions": 12
	},
	{
		"id": 5,
		"name": "Andrew",
		"question": "Sunny Park Hotel",
		"image": "https://preview.ibb.co/h5xgSn/scott_webb_67607_unsplash.jpg",
		"member": "7 hours",
		"last_seen": "Monday",
		"more_activities": false,
		"commented": 4,
		"is_new": true,
		"peers": 44,
		"discussions": 33,
		"findings": 88,
		"questions": 123
	},
	{
		"id": 6,
		"name": "Marek",
		"question": "Modest Nugget Hotel",
		"image": "https://preview.ibb.co/bBxsYS/christoph_schulz_559688_unsplash.jpg",
		"member": "2 years",
		"last_seen": "now",
		"more_activities": true,
		"activities_number": 7,
		"commented": 4,
		"is_new": true,
		"peers": 41,
		"discussions": 32,
		"findings": 11,
		"questions": 33
	},
	{
		"id": 7,
		"name": "Arek",
		"question": "Light Shore Resort",
		"image": "https://preview.ibb.co/k237YS/park_troopers_221404_unsplash.jpg",
		"member": "9 years",
		"last_seen": "2 hours ago",
		"more_activities": true,
		"activities_number": 4,
		"commented": 1,
		"is_new": true,
		"peers": 87,
		"discussions": 34,
		"findings": 73,
		"questions": 34
	},
	{
		"id": 8,
		"name": "Jarek",
		"question": "Crown Hotel",
		"image": "https://preview.ibb.co/eoD207/nichlas_andersen_225986_unsplash.jpg",
		"member": "1 month",
		"last_seen": "8 hours ago",
		"more_activities": true,
		"activities_number": 91,
		"commented": 3,
		"is_new": true,
		"peers": 12,
		"discussions": 12,
		"findings": 5,
		"questions": 7
	}
];

export default app_data;